Repository hapijs/lab, pull requests merged in 2018-03, with the labels that each got.

#817 Bump diff to 3.5 (v14.x.x)
  package.json
Labels: dependency

#816 Bump diff to 3.5
  package.json
Labels: dependency, security

#819 Implement minimum assertions threshold. Closes #690.
  README.md
  lib/cli.js
  lib/runner.js
  test/cli.js
  test/cli_plan/simple.js
  test/runner.js
Labels: enhancement

#820 Ignore default-plan-threshold for anything else than tests
  lib/runner.js
  test/runner.js
Labels: bug

#821 Update eslint
  README.md
  package.json
Labels: dependency
