Repository hapijs/lab, pull requests merged in 2018-11, with the labels that each got.

#871 Improve console coverage report readability
  lib/reporters/console.js
  test/coverage/console-large-file.js
  test/coverage/console.js
  test/reporters.js
Labels: enhancement

#875 Revert console cov report truncation
  lib/reporters/console.js
  test/reporters.js
Labels: non-issue

#876 Update dependencies
  package.json
Labels: dependency

#877 Add --coverage-all option
  README.md
  lib/cli.js
  lib/coverage.js
  test/cli.js
  test/coverage.js
  test/coverage/coverage-all/covered.js
  test/coverage/coverage-all/nested-folder/uncovered.js
Labels: enhancement

#881 Add coverage-pattern option
  README.md
  lib/cli.js
  lib/coverage.js
  test/cli.js
  test/coverage.js
Labels: enhancement

#878 Fix false-positive coverage of if statements (REDUCES REPORTED COVERAGE!)
  lib/coverage.js
  test/coverage.js
  test/coverage/conditional-value2.js
Labels: breaking changes

#882 Add missing coverage and remove unnecessary checks
  lib/leaks.js
  lib/lint.js
  lib/reporters/console.js
  lib/reporters/json.js
  lib/reporters/tap.js
  test/coverage.js
  test/coverage/switch.js
  test/lint/eslint/fix/success.js
  test/linters.js
  test/reporters.js
  test/runner.js
Labels: test

#884 Remove old parallel flag from test
  test/reporters.js
Labels: maintenance

#885 Centralize espree options
  lib/coverage.js
  lib/linter/.eslintrc.js
Labels: maintenance

#883 Use correct gray color code
  lib/reporters/console.js
  lib/runner.js
  test/reporters.js
Labels: bug

#889 Remove docs about custom linter option
  README.md
Labels: documentation

#888 Compare coverage pattern to canonical path
  lib/coverage.js
Labels: bug

#890 Remove deprecated espree option
  lib/linter/.eslintrc.js
  package.json
Labels: maintenance

#891 Update eslint version
  package.json
Labels: dependency, maintenance

#892 Add note about how to get a tests ID
  README.md
Labels: documentation

#894 Have correct exit code with multiple reporters
  bin/lab
  lib/reporters/multiple.js
  test/cli.js
  test/cli_throws/throws.js
  test/reporters.js
Labels: breaking changes, bug

#895 Fix coverage with sourcemaps inlined via Transform API.
  lib/coverage.js
  lib/reporters/multiple.js
  lib/runner.js
  package.json
  test/cli.js
  test/coverage.js
  test/coverage/sourcemaps-transformed.inl
  test/runner.js
  test/transform.js
Labels: bug
