Repository hapijs/lab, pull requests merged in 2018-07, with the labels that each got.

#840 update eslint-config-hapi dependency
  lib/cli.js
  lib/coverage.js
  lib/index.js
  lib/reporters/console.js
  lib/reporters/html.js
  lib/reporters/tap.js
  lib/runner.js
  package.json
  test/coverage.js
  test/reporters.js
  test/run_cli.js
  test/transform.js
Labels: breaking changes

#843 Allow custom handling for global errors/rejections
  README.md
  lib/runner.js
  test/cli.js
  test/cli_error/failure.js
Labels: enhancement

#844 Disable dep timeout, which is doc default
  lib/cli.js
  test/cli.js
  test/cli_timeout/before.js
Labels: breaking changes, bug
