Repository hapijs/lab, pull requests merged in 2018-10, with the labels that each got.

#860 Fixed skipped console output color
  lib/reporters/console.js
Labels: bug

#864 Add testsuites output to junit
  .travis.yml
  lib/reporters/junit.js
  lib/reporters/junit/report.xml
  test/cli.js
Labels: breaking changes, enhancement

#865 handle queueMicrotask global added in Node 11
  lib/leaks.js
Labels: maintenance

#866 Add node 11 to travis
  .travis.yml
Labels: maintenance

#867 No longer skip scripts when multiple only
  lib/runner.js
  test/cli.js
  test/reporters.js
Labels: bug

#869 [ENHANCEMENT] Nullified test context on finish to prevent memory leaks
  lib/runner.js
  test/runner.js
Labels: bug

#870 Update type definitions to match documented API
  index.d.ts
Labels: bug
