Repository hapijs/lab, pull requests merged in 2018-02, with the labels that each got.

#808 add URL and URLSearchParams to global variables
  lib/leaks.js
Labels: maintenance

#809 Update eslint version
  package.json
Labels: dependency

#810 Write CLI errors to stderr
  lib/cli.js
  test/cli.js
Labels: bug

#811 Can exclude files from coverage
  lib/coverage.js
  test/cli.js
  test/coverage.js
Labels: enhancement

#813 Fail test if a falsy value is thrown by the test
  lib/runner.js
  test/runner.js
Labels: bug

#815 Update eslint dep
  package.json
Labels: dependency
