Repository hapijs/lab, pull requests merged in 2020-09, with the labels that each got.

#995 Wait for pending ticks started by test
  lib/runner.js
  test/cli.js
  test/cli_nexttick/test.js
Labels: feature

#990 Use eslint-plugin-hapi embedded config
  API.md
  lib/linter/.eslintrc.js
  package.json
Labels: feature

#992 Allow typescript to be updated by clients
  .gitignore
  .travis.yml
  lib/cli.js
  lib/index.js
  lib/modules/coverage.js
  lib/modules/index.js
  lib/modules/leaks.js
  lib/modules/lint.js
  lib/modules/transform.js
  lib/modules/types.js
  lib/runner.js
  package.json
  test/linters.js
  test/runner.js
  test/transform.js
  test/types.js
Labels: breaking changes, dependency

#993 Shallow clone context
  API.md
  lib/runner.js
  test/runner.js
Labels: breaking changes
