Repository hapijs/lab, pull requests merged in 2022-05, with the labels that each got.

#1048 Update target to ES2020 to match node 14+
  lib/modules/types.js
Labels: feature

#1047 Fix coverage ignore flag when ts comments are removed
  lib/modules/typescript.js
  test/cli_typescript/api.ts
  test/cli_typescript/tsconfig.json
Labels: bug

#1050 Upgrade dependences
  package.json
Labels: breaking changes, dependency

#1051 Add check for TS error 2820
  lib/modules/types.js
Labels: bug
