Repository hapijs/lab, pull requests merged in 2022-04, with the labels that each got.

#1031 Support for ES modules
  API.md
  lib/cli.js
  lib/index.js
  lib/linter/index.js
  lib/runner.js
  package.json
  test/cli.js
  test/cli_esm/api.js
  test/cli_esm/commonjs-api.cjs
  test/cli_esm/commonjs-simple.cjs
  test/cli_esm/error.js
  test/cli_esm/package.json
  test/cli_esm/simple.js
  test/lint/eslint/esm/.eslintrc.cjs
  test/lint/eslint/esm/fail.js
  test/lint/eslint/esm/package.json
  test/linters.js
Labels: feature

#1032 add Node.js 18 globals
  lib/modules/leaks.js
Labels: feature

#1034 Drop support for node v12
  .github/workflows/ci-module.yml
  lib/cli.js
  lib/index.js
  lib/modules/coverage.js
  lib/reporters/console.js
  lib/reporters/index.js
  lib/reporters/json.js
  lib/runner.js
Labels: breaking changes

#1039 Update diff package
  package.json
Labels: breaking changes, dependency

#1038 Update sindresorhus deps to pre ESM versions
  package.json
Labels: dependency

#1042 Remove node 8 compat fix
  lib/reporters/console.js
Labels: feature

#1036 Coverage for nullish coalescing operator
  lib/modules/coverage.js
  package.json
  test/coverage.js
  test/coverage/conditional-coalesce.js
  test/coverage/conditional-coalesce2.js
Labels: feature

#1035 Upgrade to eslint v8
  lib/cli.js
  lib/index.js
  lib/linter/index.js
  lib/modules/coverage.js
  lib/modules/typescript.js
  package.json
  test/coverage.js
  test/reporters.js
  test/transform.js
  test/typescript.js
Labels: feature, breaking changes, dependency

#1043 New --coverage-predicates option
  .labrc.js
  API.md
  lib/cli.js
  lib/index.d.ts
  lib/modules/coverage.js
  lib/reporters/console.js
  test/coverage.js
  test/coverage/bypass-predicated.js
  test/coverage/ignore-predicated-fail.js
  test/coverage/ignore-predicated.js
  test/reporters.js
Labels: feature

#1044 Revise leak detection to use fresh node globals
  .github/workflows/ci-module.yml
  lib/modules/leaks.js
  lib/runner.js
  test/leaks.js
Labels: feature

#1037 Remove undocumented --coverage-module option
  lib/cli.js
  lib/index.d.ts
  lib/modules/coverage.js
  lib/reporters/console.js
  lib/reporters/index.js
  package.json
  test/coverage.js
  test/reporters.js
Labels: feature, breaking changes

#1045 Support node v18
  lib/modules/coverage.js
  lib/reporters/html.js
  lib/source-map.js
  lib/utils.js
  test/utils.js
Labels: feature, dependency
